# Plex/docker-compose.yml

version: "3"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europa/Copenhagen
      - AUTO_UPDATE=true #optional
    volumes:
      - /jackett:/config
      - /download/downloading:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europa/Copenhagen
    volumes:
      - /radarr:/config
      - /plex/media/movies:/movies #optional
      - /download/download_completed:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europa/Copenhagen
    volumes:
      - /sonarr:/config
      - /plex/media/Shows:/shows #optional
      - /download/downloading_completed:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europa/Copenhagen
    volumes:
      - /tautalli:/config
    ports:
      - 8181:8181
    restart: unless-stopped

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europa/Copenhagen
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /deluge:/config
      - /downloads:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europa/Copenhagen
    volumes:
      - /ombi:/config
    ports:
      - 3579:3579
    restart: unless-stopped
